const PAYMENT_STATUSES = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  REQUESTED: "REQUESTED",
};

const PAYMENT_RESPONSE_CODES = {
  PAID: "PAID",
  NOT_PAID: "NOT_PAID",
};

const EVENTS = {
  TEST: "TEST",
  USER_REGISTERED: "USER_REGISTERED",
  CHALLANGE_PURCHASED: "CHALLANGE_PURCHASED",
};

const TRADING_ACCOUNT_STATUS = {
  ACTIVE: "ACTIVE",
  LOSE: "LOSE",
  PASSED: "PASSED",
};

const MT5_SERVER_TYPE = {
  LIVE: "LIVE",
  DEMO: "DEMO",
};

const MT5_GROUP_TYPE = {
  PRO: "real\\pro",
  STANDART: "real\\standart",
};

module.exports = {
  PAYMENT_STATUSES,
  PAYMENT_RESPONSE_CODES,
  EVENTS,
  TRADING_ACCOUNT_STATUS,
  MT5_SERVER_TYPE,
  MT5_GROUP_TYPE,
};
